# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NIU Mars Rover
email: niurover@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Open to all majors, the NIU Mars Rover team is a student organization in NIU’s College of Engineering and Engineering Technology. This team offers students education and experience relating to the design, fabrication, and integration of mechanical, electrical, and computer systems relevant to our rover’s operation. Our main competition is the University Rover Challenge, held each year in May.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://niurover.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown

collections:
  join:
    output: true
    permalink: /join/:name
  about:
    output: true
    permalink: /about/:name
